### ISSUE TITLE
NullReferenceException for null result

### ISSUE THREAD

**Issue by jarocki76** [jweber/WcfClientProxyGenerator#12]
Hi.
Recently I upgraded WcfClientProxygenerator from version 1.2.5 to 2.1.0.
Now, when I try to call a WCF service method that returns null, I get NullReferenceException from client proxy:

```csharp
   at WcfClientProxyGenerator.RetryingWcfActionInvoker`1.HandleOnAfterInvoke(Int32 retryCounter, Object response, InvokeInfo invokeInfo)
   at WcfClientProxyGenerator.RetryingWcfActionInvoker`1.Invoke[TResponse](Func`2 method, InvokeInfo invokeInfo)
   at WcfClientProxyGenerator.DynamicProxy.ICaseService.GetTotalItemCount(FilterModel filter)
   at TestWcfClient.Program.Main(String[] args) in c:\Users\j.leszczynski\Documents\Visual Studio 2013\Projects\TestWcfClient\TestWcfClient\Program.cs:line 17
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Service method
```csharp
public string GeString()
    {
      return null;
    }
```

Client method
```csharp
static void Main(string[] args)
    {
      var client = WcfClientProxyGenerator.WcfClientProxy.Create<ICaseService>();

      var result = client.GeString();
    }
```

**Comment by jweber** [comment]
This has been fixed in [2.1.1](../releases/tag/v2.1.1) and the release is up on NuGet at this time. Thanks for the report!
